#!/usr/bin/env python3
"""
envato_assets.py - fetch and cache real Envato Elements assets for layering.

The crisp components (interface panels, stamps, charts) come from real Envato
assets composited on top of the NB2 scene, instead of being generated by the
model. Generated props soften and garble text; real assets stay razor-sharp.
That sharpness is the trust signal for a skeptical audience.

This module does NOT call the network from the chat environment (egress is
blocked). On James's machine, Claude Code resolves Envato asset ids through the
connected Envato MCP and drops the downloaded files into assets/envato/<id>.png.
This helper just resolves an id (or a local path) to a usable RGBA image and
caches it.

Concept JSON carries the asset like this:
  "asset": { "type": "interface_panel", "id": "<envato_id_or_local_filename>",
             "zone": "right", "scale": 0.46 }

- type   : which component the asset stands in for (informational)
- id     : Envato item id, OR a filename already sitting in assets/envato/
- zone   : where to place it: left | right | center | full
- scale  : fraction of canvas WIDTH the asset should span (0.2 - 0.6 typical)
"""

from pathlib import Path
from PIL import Image

ASSET_DIR = Path("assets/envato")


def resolve_asset(asset_id: str):
    """
    Return a Path to a local PNG for this asset id, or None if not present.
    Claude Code (with the Envato MCP) is responsible for having placed the file
    at assets/envato/<id>.png beforehand. We accept either a bare id or a
    filename, and we try a few sensible extensions.
    """
    ASSET_DIR.mkdir(parents=True, exist_ok=True)
    cand = Path(asset_id)
    if cand.exists():
        return cand
    for ext in ("", ".png", ".jpg", ".jpeg", ".webp"):
        p = ASSET_DIR / f"{asset_id}{ext}"
        if p.exists():
            return p
    return None


def load_asset_rgba(asset_id: str):
    """Load the asset as RGBA, or None if it isn't on disk yet."""
    p = resolve_asset(asset_id)
    if not p:
        return None
    try:
        return Image.open(p).convert("RGBA")
    except Exception as e:
        print(f"   asset load failed for {asset_id}: {e}")
        return None


# ---------------------------------------------------------------------------
# OPTIONAL: Envato MARKET catalog search via personal API token.
# This is a DISCOVERY aid only. The token (ENVATO_API_TOKEN in .env) talks to the
# Envato Market API and returns item metadata. It does NOT download licensed Envato
# Elements files; those come through the connected Envato MCP into assets/envato/.
# Use this when you want to look up Market items by keyword from code.
# ---------------------------------------------------------------------------
import os
import json as _json
import urllib.request as _urlreq
import urllib.parse as _urlparse


def _envato_token():
    tok = os.environ.get("ENVATO_API_TOKEN", "").strip()
    return tok or None


def market_search(term: str, site: str = "graphicriver", page: int = 1):
    """
    Search the Envato MARKET catalog by keyword. Returns a list of
    {id, name, url, preview} dicts, or [] if no token / on error.
    Discovery only. Does not download. Elements assets are NOT covered here.
    """
    tok = _envato_token()
    if not tok:
        print("   ENVATO_API_TOKEN not set in .env; skipping Market search.")
        return []
    q = _urlparse.urlencode({"term": term, "site": f"{site}.net", "page": page})
    url = f"https://api.envato.com/v1/discovery/search/search/item?{q}"
    req = _urlreq.Request(url, headers={"Authorization": f"Bearer {tok}",
                                        "User-Agent": "godiva-thumbnails"})
    try:
        with _urlreq.urlopen(req, timeout=15) as r:
            data = _json.loads(r.read().decode())
    except Exception as e:
        print(f"   Envato Market search failed: {e}")
        return []
    out = []
    for it in data.get("matches", [])[:10]:
        out.append({"id": it.get("id"), "name": it.get("name"),
                    "url": it.get("url"), "preview": (it.get("previews") or {})})
    return out
